/** This file is generated by scripts/generate_contract_bindings.py. Do not edit it by hand. */

export const SCHEMA_DIGESTS: Record<string, string> = {
  'approval.schema.json': 'd324217014f3457394f819abc4fffe0938219113b720a675c9d4e544108e4da0',
  'common.schema.json': '7461d10941b092d3fd118e6b87ee4357a3157959b278e64108dd713a164c7802',
  'evidence-envelope.schema.json': '181d7e3ffd00f49867e70185291a0393a70d3f44b944c0d4358fd9b8fc299a53',
  'execution-grant.schema.json': '6509fa2b1622b36400d51ab80d147db8d90258437b8fae4f3d7c684f1d336cb4',
  'outcome-record.schema.json': 'fc4f9078aca36c8d40253ff60d76944a41cb9d9fa26f35974395ec46f895552d',
  'run-manifest.schema.json': '577777fd5b01253c45879c8353df07128fa8e07b8952232895d3e1903380c2b1',
};

export const RUN_STATUSES = ['QUEUED', 'LEASED', 'RUNNING', 'FINALIZING', 'COMPLETED', 'INTERRUPTED', 'CANCELLED'] as const;
export type RunStatus = (typeof RUN_STATUSES)[number];

export const OUTCOMES = ['NOT_EVALUATED', 'PASS', 'FAIL', 'INCONCLUSIVE'] as const;
export type Outcome = (typeof OUTCOMES)[number];

export const CONDITIONS = ['TRUE', 'FALSE', 'UNKNOWN'] as const;
export type Condition = (typeof CONDITIONS)[number];

export const APPROVAL_SCOPES = ['RUN_EFFECTS', 'PATCH_APPLY', 'GITHUB_PUBLISH'] as const;
export type ApprovalScope = (typeof APPROVAL_SCOPES)[number];

export const AT_ACTIONS = ['NEXT', 'PREVIOUS', 'ACTIVATE', 'TYPE_TEXT', 'KEY_CHORD', 'READ_CURRENT', 'WAIT_FOR_READER_IDLE', 'STOP'] as const;
export type AtAction = (typeof AT_ACTIONS)[number];

export const EVENT_TYPES = ['RUN_STARTED', 'PREFLIGHT_RESULT', 'ACTION_INTENT', 'ACTION_RESULT', 'READER_OBSERVATION', 'ASSERTION_OBSERVATION', 'EFFECT_RECEIPT', 'BUDGET_EVENT', 'INTERRUPTION', 'RUN_FINISHED'] as const;
export type EventType = (typeof EVENT_TYPES)[number];
