// Generated by scripts/generate_reference_fixture.py; do not edit by hand.
export const REFERENCE_FIXTURE_VERSION = 'accessforge.reference-service-request/1' as const;
export const REFERENCE_FIXTURE_DIGEST = '39acd4e6ff833c3f5668cbc951f541658858568bd9ba31814bfb19a318dbb6a3' as const;
