"""Generated by scripts/generate_reference_fixture.py; do not edit by hand."""

from typing import Final

REFERENCE_FIXTURE_VERSION: Final = "accessforge.reference-service-request/1"
REFERENCE_FIXTURE_DIGEST: Final = "39acd4e6ff833c3f5668cbc951f541658858568bd9ba31814bfb19a318dbb6a3"
