#!/usr/bin/env python
"""Generate language bindings from the JSON Schemas.

The schemas are authoritative. These outputs are derived, and are committed only so that drift can
be detected: CI regenerates them and fails if the working tree changes. Editing a generated file
by hand is therefore self-defeating — the next CI run will overwrite the intent and fail.

What is generated:

* the digest of every schema, so a schema edit that nobody propagated is caught;
* the enumerations that both languages must agree on (run status, outcome, condition, approval
  scope, assistive-technology actions, event types), extracted from common.schema.json rather
  than retyped in two places.

Run:  uv run python scripts/generate_contract_bindings.py
Check: uv run python scripts/generate_contract_bindings.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
SCHEMA_DIR = REPO / "packages/contracts/schemas"
PY_OUT = REPO / "packages/contracts/python/src/accessforge_contracts/_generated.py"
TS_OUT = REPO / "packages/contracts/ts/src/generated.ts"

# Enumerations both languages must agree on, by their $defs name in common.schema.json.
# (schema $defs name, generated constant name, generated TypeScript type name).
# The type name is explicit rather than derived: a plural-stripping heuristic turned
# RUN_STATUSES into "RunStatuse".
SHARED_ENUMS = [
    ("runStatus", "RUN_STATUSES", "RunStatus"),
    ("outcome", "OUTCOMES", "Outcome"),
    ("condition", "CONDITIONS", "Condition"),
    ("approvalScope", "APPROVAL_SCOPES", "ApprovalScope"),
    ("atAction", "AT_ACTIONS", "AtAction"),
    ("eventType", "EVENT_TYPES", "EventType"),
]

BANNER = "This file is generated by scripts/generate_contract_bindings.py. Do not edit it by hand."


def _load(name: str) -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads((SCHEMA_DIR / name).read_text(encoding="utf-8"))
    return loaded


def _schema_names() -> list[str]:
    return sorted(p.name for p in SCHEMA_DIR.glob("*.schema.json"))


def _digests() -> dict[str, str]:
    sys.path.insert(0, str(REPO / "packages/domain/src"))
    from accessforge_domain.canonical import digest  # noqa: PLC0415

    return {name: digest(_load(name)) for name in _schema_names()}


def _enums() -> dict[str, tuple[list[str], str]]:
    common = _load("common.schema.json")["$defs"]
    return {
        const_name: (list(common[def_name]["enum"]), type_name)
        for def_name, const_name, type_name in SHARED_ENUMS
    }


def render_python(digests: dict[str, str], enums: dict[str, tuple[list[str], str]]) -> str:
    lines = [
        f'"""{BANNER}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final",
        "",
        "SCHEMA_DIGESTS: Final[dict[str, str]] = {",
    ]
    lines += [f'    "{name}": "{value}",' for name, value in sorted(digests.items())]
    lines.append("}")
    lines.append("")
    for const_name, (values, _type_name) in enums.items():
        lines.append(f"{const_name}: Final[tuple[str, ...]] = (")
        lines += [f'    "{v}",' for v in values]
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


def render_typescript(digests: dict[str, str], enums: dict[str, tuple[list[str], str]]) -> str:
    lines = [f"/** {BANNER} */", "", "export const SCHEMA_DIGESTS: Record<string, string> = {"]
    lines += [f"  '{name}': '{value}'," for name, value in sorted(digests.items())]
    lines.append("};")
    lines.append("")
    for const_name, (values, type_name) in enums.items():
        rendered = ", ".join(f"'{v}'" for v in values)
        lines.append(f"export const {const_name} = [{rendered}] as const;")
        lines.append(f"export type {type_name} = (typeof {const_name})[number];")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed bindings differ from freshly generated ones",
    )
    args = parser.parse_args()

    digests = _digests()
    enums = _enums()
    outputs = {PY_OUT: render_python(digests, enums), TS_OUT: render_typescript(digests, enums)}

    if args.check:
        stale = []
        for path, content in outputs.items():
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                stale.append(path.relative_to(REPO))
        if stale:
            print("Generated bindings are stale:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print(
                "\nRun: uv run python scripts/generate_contract_bindings.py",
                file=sys.stderr,
            )
            return 1
        print(f"bindings match schemas ({len(digests)} schemas, {len(enums)} enumerations)")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
