#!/usr/bin/env python
"""Generate the client operation surface from the published contract.

`contracts/openapi.json` is generated from the live application, so a client generated from *it* is
generated from the application. That chain is the whole point: a route whose path or method changes
produces a diff in three places on the same commit, and CI fails if any of them was not regenerated.

**What is generated, and what deliberately is not.**

Generated: the operation table — one entry per route, with its method, path, path parameters, and
whether it is a mutation. That is the part that drifts, silently, and that a person cannot check by
reading.

Not generated: the transport. Cookies, CSRF, `If-Match`, `Idempotency-Key`, retry semantics and the
handling of a problem document are decisions about how to talk to this API safely, and generating
them from a contract that does not describe them would produce a confident client that gets them
wrong. They are written once, by hand, in `packages/clients/python/src/accessforge_client/`.

Also not generated: response types. Every route on this API returns `dict[str, Any]`, so a
type-generating client would emit `Any` for every field and imply a precision that does not exist.
A client that told you `run.outcome` was a `RunOutcome` when the server promises no such thing is
worse than one that hands you the dictionary the server actually sent.

Run:  uv run python scripts/generate_clients.py
Check: uv run python scripts/generate_clients.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess  # noqa: S404 - runs this repository's own formatter
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
CONTRACT = REPO / "contracts" / "openapi.json"
PY_OUT = REPO / "packages/clients/python/src/accessforge_client/_operations.py"
TS_OUT = REPO / "packages/clients/ts/src/operations.ts"

BANNER = "This file is generated by scripts/generate_clients.py. Do not edit it by hand."

#: Methods that change something. A client has to know, because these are the ones that need a CSRF
#: header — and on this API, the ones where sending a request twice without an `Idempotency-Key` is
#: a decision rather than an accident.
MUTATING = frozenset({"post", "put", "patch", "delete"})

_PATH_PARAM = re.compile(r"\{([^}]+)\}")


def _operations() -> list[dict[str, Any]]:
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    found: list[dict[str, Any]] = []
    for path, methods in sorted(contract["paths"].items()):
        for method, operation in sorted(methods.items()):
            if not isinstance(operation, dict) or "operationId" not in operation:
                continue
            found.append(
                {
                    "operation_id": str(operation["operationId"]),
                    "method": method.upper(),
                    "path": path,
                    "parameters": _PATH_PARAM.findall(path),
                    "mutating": method in MUTATING,
                    "authenticated": bool(operation.get("security")),
                    "summary": (operation.get("summary") or "").strip(),
                }
            )
    return found


def _python(operations: list[dict[str, Any]]) -> str:
    lines = [
        '"""' + BANNER,
        "",
        "The operation table, derived from contracts/openapi.json, which is itself derived",
        "from the live application. Every entry names a real route; a route removed from the API",
        "disappears from here on the same commit, and a client calling it stops compiling rather",
        "than receiving a 404 in production.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class Operation:",
        '    """One route, as a client needs to address it."""',
        "",
        "    operation_id: str",
        "    method: str",
        "    path: str",
        "    parameters: tuple[str, ...]",
        "    mutating: bool",
        '    """Needs a CSRF header. Also the set where sending a request twice without an',
        '    Idempotency-Key is a decision rather than an accident."""',
        "",
        "    authenticated: bool",
        "",
        "    def render(self, **values: str) -> str:",
        '        """Fill the path parameters, refusing an incomplete set.',
        "",
        "        Refusing rather than leaving a `{workspace_id}` in the URL: an unsubstituted",
        "        parameter produces a 404 from a path that looks almost right, and the",
        "        missing piece is invisible in the response.",
        '        """',
        "        missing = [name for name in self.parameters if name not in values]",
        "        if missing:",
        "            raise KeyError(",
        "                f\"{self.operation_id} needs path parameter(s) {', '.join(missing)}\"",
        "            )",
        "        rendered = self.path",
        "        for name in self.parameters:",
        '            rendered = rendered.replace("{" + name + "}", str(values[name]))',
        "        return rendered",
        "",
        "",
        "OPERATIONS: dict[str, Operation] = {",
    ]
    for op in operations:
        params = ", ".join(f'"{p}"' for p in op["parameters"])
        params = f"({params},)" if len(op["parameters"]) == 1 else f"({params})"
        lines.append(f'    "{op["operation_id"]}": Operation(')
        lines.append(f'        operation_id="{op["operation_id"]}",')
        lines.append(f'        method="{op["method"]}",')
        lines.append(f'        path="{op["path"]}",')
        lines.append(f"        parameters={params},")
        lines.append(f"        mutating={op['mutating']},")
        lines.append(f"        authenticated={op['authenticated']},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append(
        "#: Every path the API serves, for a consumer checking its own URLs against reality."
    )
    lines.append("PATHS: frozenset[str] = frozenset(")
    lines.append("    {")
    for path in sorted({op["path"] for op in operations}):
        lines.append(f'        "{path}",')
    lines.append("    }")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def _typescript(operations: list[dict[str, Any]]) -> str:
    lines = [
        f"// {BANNER}",
        "//",
        "// The operation table, derived from contracts/openapi.json, which is itself derived from",
        "// the live application. `PATHS` exists so a hand-written client can assert every URL",
        "// it builds is one the API actually serves -- drift that a type checker cannot see.",
        "",
        "export interface Operation {",
        "  readonly operationId: string",
        "  readonly method: string",
        "  readonly path: string",
        "  readonly parameters: readonly string[]",
        "  /** Needs a CSRF header. */",
        "  readonly mutating: boolean",
        "  readonly authenticated: boolean",
        "}",
        "",
        "export const OPERATIONS: Readonly<Record<string, Operation>> = {",
    ]
    for op in operations:
        params = ", ".join(f"'{p}'" for p in op["parameters"])
        lines.append(f"  '{op['operation_id']}': {{")
        lines.append(f"    operationId: '{op['operation_id']}',")
        lines.append(f"    method: '{op['method']}',")
        lines.append(f"    path: '{op['path']}',")
        lines.append(f"    parameters: [{params}],")
        lines.append(f"    mutating: {str(op['mutating']).lower()},")
        lines.append(f"    authenticated: {str(op['authenticated']).lower()},")
        lines.append("  },")
    lines.append("} as const")
    lines.append("")
    lines.append("export const PATHS: readonly string[] = [")
    for path in sorted({op["path"] for op in operations}):
        lines.append(f"  '{path}',")
    lines.append("]")
    lines.append("")
    lines.append("/**")
    lines.append(" * Fill a path template, refusing an incomplete set.")
    lines.append(" *")
    lines.append(" * An unsubstituted `{workspace_id}` produces a 404 from a URL that looks almost")
    lines.append(" * right, and the missing piece is invisible in the response.")
    lines.append(" */")
    lines.append(
        "export function render(operation: Operation, values: Record<string, string>): string {"
    )
    lines.append("  const missing = operation.parameters.filter((name) => !(name in values))")
    lines.append("  if (missing.length > 0) {")
    lines.append("    throw new Error(")
    lines.append("      `${operation.operationId} needs path parameter(s) ${missing.join(', ')}`,")
    lines.append("    )")
    lines.append("  }")
    lines.append("  return operation.parameters.reduce((rendered, name) => {")
    lines.append("    const value = values[name]")
    lines.append("    if (value === undefined) {")
    lines.append("      // Unreachable after the check above, and narrowed rather than asserted:")
    lines.append("      // `values[name] as string` would silence the type checker on exactly the")
    lines.append("      // mistake it is there to catch under noUncheckedIndexedAccess.")
    lines.append("      throw new Error(`${operation.operationId} needs path parameter ${name}`)")
    lines.append("    }")
    lines.append("    return rendered.replace(`{${name}}`, value)")
    lines.append("  }, operation.path)")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _formatted(rendered: str) -> str:
    """Run the repository's own formatter over the generated Python.

    Otherwise the file is generated one way and formatted another, and `--check` fails on a tree
    nobody edited: the generator writes its version, `ruff format` rewrites it, and CI reports the
    clients as out of date on a commit that changed no routes. Making the generator emit what the
    formatter would emit removes the disagreement rather than exempting the file from it.
    """
    result = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(PY_OUT), "-"],
        input=rendered,
        capture_output=True,
        text=True,
        check=False,
        cwd=REPO,
    )
    if result.returncode != 0:
        raise SystemExit(f"ruff format refused the generated client: {result.stderr.strip()}")
    return result.stdout


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    operations = _operations()
    if not operations:
        print(
            "the contract declares no operations; refusing to write an empty client",
            file=sys.stderr,
        )
        return 1

    outputs = {PY_OUT: _formatted(_python(operations)), TS_OUT: _typescript(operations)}
    stale = []
    for path, rendered in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != rendered:
            stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered, encoding="utf-8")

    if args.check:
        if stale:
            print(
                "generated clients are out of date: "
                + ", ".join(str(p.relative_to(REPO)) for p in stale)
                + "\nThe API changed shape without its clients changing with it. Run: "
                "uv run python scripts/generate_clients.py",
                file=sys.stderr,
            )
            return 1
        print(f"clients match the contract ({len(operations)} operations)")
        return 0

    print(f"wrote {len(operations)} operations to 2 client(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
