"""Generate a frozen logical fixture identity, independently of patchable presentation bytes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from accessforge_domain.canonical import digest

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/contracts/fixtures/reference-service-request-v1.json"
PYTHON = (
    ROOT / "packages/contracts/python/src/accessforge_contracts/reference_fixture.py",
    ROOT / "fixtures/reference-app/src/reference_app/fixture_contract.py",
)
TYPESCRIPT = ROOT / "packages/contracts/ts/src/reference-fixture.ts"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    definition = json.loads(SOURCE.read_text())
    version = definition["identityVersion"]
    if version != "accessforge.reference-service-request/1":
        raise ValueError("the v1 fixture file must retain its explicit identity version")
    identity = digest(definition)
    banner = "Generated by scripts/generate_reference_fixture.py; do not edit by hand."
    python = (
        f'"""{banner}"""\n\nfrom typing import Final\n\n'
        f'REFERENCE_FIXTURE_VERSION: Final = "{version}"\n'
        f'REFERENCE_FIXTURE_DIGEST: Final = "{identity}"\n'
    )
    typescript = (
        f"// {banner}\n"
        f"export const REFERENCE_FIXTURE_VERSION = '{version}' as const;\n"
        f"export const REFERENCE_FIXTURE_DIGEST = '{identity}' as const;\n"
    )
    changed: list[str] = []
    for path, content in [*((path, python) for path in PYTHON), (TYPESCRIPT, typescript)]:
        if path.exists() and path.read_text() == content:
            continue
        changed.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.write_text(content)
    if args.check and changed:
        print("fixture identity bindings differ: " + ", ".join(changed))
        return 1
    print("logical fixture identity: " + version + " " + identity)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
