"""This file is generated by scripts/generate_contract_bindings.py. Do not edit it by hand."""

from __future__ import annotations

from typing import Final

SCHEMA_DIGESTS: Final[dict[str, str]] = {
    "approval.schema.json": "d324217014f3457394f819abc4fffe0938219113b720a675c9d4e544108e4da0",
    "common.schema.json": "fbafe43b9bfee896a00c01843ff66e9ec7899b108818635f112d3b68fdd0db72",
    "evidence-envelope.schema.json": "181d7e3ffd00f49867e70185291a0393a70d3f44b944c0d4358fd9b8fc299a53",
    "execution-grant.schema.json": "6509fa2b1622b36400d51ab80d147db8d90258437b8fae4f3d7c684f1d336cb4",
    "outcome-record.schema.json": "fc4f9078aca36c8d40253ff60d76944a41cb9d9fa26f35974395ec46f895552d",
    "run-manifest.schema.json": "577777fd5b01253c45879c8353df07128fa8e07b8952232895d3e1903380c2b1",
}

RUN_STATUSES: Final[tuple[str, ...]] = (
    "QUEUED",
    "LEASED",
    "RUNNING",
    "FINALIZING",
    "COMPLETED",
    "INTERRUPTED",
    "CANCELLED",
)

OUTCOMES: Final[tuple[str, ...]] = (
    "NOT_EVALUATED",
    "PASS",
    "FAIL",
    "INCONCLUSIVE",
)

CONDITIONS: Final[tuple[str, ...]] = (
    "TRUE",
    "FALSE",
    "UNKNOWN",
)

APPROVAL_SCOPES: Final[tuple[str, ...]] = (
    "RUN_EFFECTS",
    "PATCH_APPLY",
    "GITHUB_PUBLISH",
)

AT_ACTIONS: Final[tuple[str, ...]] = (
    "NEXT",
    "PREVIOUS",
    "ACTIVATE",
    "TYPE_TEXT",
    "KEY_CHORD",
    "READ_CURRENT",
    "WAIT_FOR_READER_IDLE",
    "STOP",
)

EVENT_TYPES: Final[tuple[str, ...]] = (
    "RUN_STARTED",
    "PREFLIGHT_RESULT",
    "ACTION_INTENT",
    "ACTION_RESULT",
    "READER_OBSERVATION",
    "ASSERTION_OBSERVATION",
    "EFFECT_RECEIPT",
    "BUDGET_EVENT",
    "INTERRUPTION",
    "RUN_FINISHED",
)
