"""The outcome verifier: identity, provenance, precedence and what a PASS establishes.

The negative cases the module prompt lists: prior-fixture receipt, supervisor-forged observer
record, missing producer tail, wrong phrase provenance, simultaneous FALSE/UNKNOWN, false completion
with all other assertions true, failure plus corrupt artifact, and a model PASS.

These fixtures are constructed here, not produced by the evaluation code path, which the prompt asks
for explicitly: "independent offline/unit test fixtures not generated by the same code path as
evaluation". A fixture built by calling the thing under test agrees with it by construction.

Requirements: FR-006, FR-007, FR-011, FR-023.
Invariants: INV-01 through INV-06, INV-11, INV-12, INV-16.
"""

from __future__ import annotations

import pytest

from accessforge_domain.evaluation import (
    ALWAYS_REQUIRED,
    PASS_SCOPE_STATEMENT,
    AssertionOutcome,
    CompletionObservation,
    EffectCount,
    IdentityKind,
    ObserverError,
    Provenance,
    ProvenanceError,
    assert_provenance_permitted,
    decide,
    evaluate_assertions,
    observe_completion,
    observer_writes_nothing,
    revalidate,
)
from accessforge_domain.journeys.assertions import (
    Assertion,
    AssertionKind,
    Observer,
    UnknownReason,
)
from accessforge_domain.states import Condition, FindingStatus, Outcome

EVALUATOR = "evaluator@1.4.0"
EVIDENCE_SET = "d" * 64
NONCE = "nonce-run-1"

#: Identities written out rather than generated, so the table below is readable and the fixture is
#: independent of anything that builds one.
SEALED = {
    IdentityKind.SOURCE: "source-aaa",
    IdentityKind.BUILD: "build-bbb",
    IdentityKind.ENVIRONMENT: "env-ccc",
    IdentityKind.RUNNER_PROFILE: "profile-ddd",
    IdentityKind.EVALUATOR: EVALUATOR,
    IdentityKind.JOURNEY_VERSION: "journey-eee",
    IdentityKind.ASSERTION_SET: "assertions-fff",
    IdentityKind.FIXTURE_INSTANCE: "fixture-ggg",
}

COMPLETION = Assertion(
    assertion_id="completion.one-request",
    kind=AssertionKind.TASK_COMPLETION,
    description="The application holds exactly one service request for this run's fixture.",
    required=True,
    unknown_reasons=frozenset({UnknownReason.OBSERVER_UNREACHABLE}),
)
ANNOUNCEMENT = Assertion(
    assertion_id="announcement.validation-error",
    kind=AssertionKind.REQUIRED_ANNOUNCEMENT,
    description="The reader announces that the email field is invalid.",
    required=True,
    unknown_reasons=frozenset(
        {UnknownReason.READER_UNAVAILABLE, UnknownReason.OBSERVATION_MISSING}
    ),
)


def _value(
    assertion: Assertion,
    condition: Condition,
    *,
    provenance: Provenance = Provenance.OBSERVER_AUTHORED,
    refs: tuple[str, ...] = ("event:7",),
    unknown_reason: str | None = None,
) -> AssertionOutcome:
    return AssertionOutcome(
        assertion_id=assertion.assertion_id,
        kind=assertion.kind,
        condition=condition,
        provenance=provenance,
        evidence_refs=() if condition is Condition.UNKNOWN else refs,
        unknown_reason=unknown_reason
        or ("not observed" if condition is Condition.UNKNOWN else None),
    )


def _decide(
    *,
    assertion_values: dict[str, AssertionOutcome] | None = None,
    completion: CompletionObservation | None = None,
    observed_identities: dict[IdentityKind, str] | None = None,
    completeness_reasons: tuple[str, ...] = (),
    preflight_passed: bool = True,
):
    values = (
        assertion_values
        if assertion_values is not None
        else {ANNOUNCEMENT.assertion_id: _value(ANNOUNCEMENT, Condition.TRUE)}
    )
    return decide(
        identity=revalidate(
            SEALED, observed_identities if observed_identities is not None else SEALED
        ),
        completeness_reasons=completeness_reasons,
        preflight_passed=preflight_passed,
        assertions=evaluate_assertions((ANNOUNCEMENT,), values),
        completion=completion
        or CompletionObservation(condition=Condition.TRUE, detail="one request", observed_count=1),
        evaluator_version=EVALUATOR,
        evidence_set_digest=EVIDENCE_SET,
    )


# --- the allowed path ----------------------------------------------------------------------------


def test_a_sound_complete_all_true_run_passes() -> None:
    """The control. Every refusal below is meaningless against a verifier that never passes."""
    verdict = _decide()
    assert verdict.outcome is Outcome.PASS
    assert verdict.reasons == ()


def test_a_pass_carries_its_scope_statement() -> None:
    """Attached to the verdict rather than kept in documentation, because a verdict travels into
    exports and dashboards and the caveat has to travel with it."""
    verdict = _decide()
    assert verdict.scope == PASS_SCOPE_STATEMENT
    for claim in ("people with disabilities in general", "legal", "does not replace"):
        assert claim in verdict.scope


def test_a_verdict_records_the_evaluator_and_the_evidence_it_read() -> None:
    """Without both, a recomputation cannot be compared against the original."""
    verdict = _decide()
    assert verdict.evaluator_version == EVALUATOR
    assert verdict.evidence_set_digest == EVIDENCE_SET


def test_evaluation_is_deterministic() -> None:
    """No clock, no model, no confidence score in the path. This is the property the export story
    rests on: anyone holding the evidence recomputes the same answer."""
    assert _decide() == _decide()


# --- identity before observations ----------------------------------------------------------------


@pytest.mark.parametrize("kind", sorted(ALWAYS_REQUIRED))
def test_any_changed_identity_makes_the_run_inconclusive(kind: IdentityKind) -> None:
    """Every identity, not the ones an author remembered. INV-03."""
    observed = dict(SEALED)
    observed[kind] = "something-else"
    verdict = _decide(observed_identities=observed)
    assert verdict.outcome is Outcome.INCONCLUSIVE
    assert any(kind in r for r in verdict.reasons)


@pytest.mark.parametrize("kind", sorted(ALWAYS_REQUIRED))
def test_any_missing_identity_makes_the_run_inconclusive(kind: IdentityKind) -> None:
    observed = {k: v for k, v in SEALED.items() if k != kind}
    verdict = _decide(observed_identities=observed)
    assert verdict.outcome is Outcome.INCONCLUSIVE


def test_an_identity_mismatch_outranks_every_favourable_observation() -> None:
    """The ordering task 1 of the prompt asks for: reject changed identities *before* considering
    favorable observations. Every assertion here is TRUE and the run still establishes nothing."""
    observed = dict(SEALED)
    observed[IdentityKind.BUILD] = "a-different-build"
    verdict = _decide(observed_identities=observed)
    assert verdict.outcome is Outcome.INCONCLUSIVE


def test_the_three_identity_failures_are_distinguished() -> None:
    """Sealed-but-unreported, reported-but-different, and never-sealed lead somewhere different.
    Collapsing them sends someone to compare two digests when one was never recorded."""
    never_sealed = revalidate({k: v for k, v in SEALED.items() if k != IdentityKind.BUILD}, SEALED)
    assert any("not bound by the sealed manifest" in r for r in never_sealed.reasons)

    unreported = revalidate(SEALED, {k: v for k, v in SEALED.items() if k != IdentityKind.BUILD})
    assert any("does not report it" in r for r in unreported.reasons)

    different = revalidate(SEALED, {**SEALED, IdentityKind.BUILD: "other"})
    assert any("changed:" in r for r in different.reasons)


def test_a_model_is_optional_but_not_ignorable() -> None:
    """A scripted navigator legitimately has no model. A run driven by a *different* model than the
    one approved is not the approved run, and accepting it silently is how a substitution lands."""
    assert revalidate(SEALED, SEALED).bound, "no model anywhere is fine"

    substituted = revalidate(SEALED, {**SEALED, IdentityKind.MODEL: "some-other-model"})
    assert not substituted.bound
    assert any("different model" in r for r in substituted.reasons)

    sealed_with_model = {**SEALED, IdentityKind.MODEL: "approved-model"}
    unreported = revalidate(sealed_with_model, SEALED)
    assert not unreported.bound
    assert any("does not report which model ran" in r for r in unreported.reasons)

    matching = revalidate(sealed_with_model, sealed_with_model)
    assert matching.bound


# --- precedence ----------------------------------------------------------------------------------


def test_unknown_outranks_a_simultaneous_false() -> None:
    """A run that observed one genuine failure *and* failed to observe something else is
    INCONCLUSIVE, not FAIL. The unobserved condition might have changed how the failure reads, and
    reporting a confirmed defect on incomplete evidence is the harm INV-02 forbids."""
    second = Assertion(
        assertion_id="focus.moves-to-error",
        kind=AssertionKind.FOCUS_BEHAVIOUR,
        description="Focus moves to the first invalid field.",
        required=True,
        unknown_reasons=frozenset({UnknownReason.OBSERVATION_MISSING}),
    )
    evaluation = evaluate_assertions(
        (ANNOUNCEMENT, second),
        {
            ANNOUNCEMENT.assertion_id: _value(ANNOUNCEMENT, Condition.FALSE),
            second.assertion_id: _value(second, Condition.UNKNOWN),
        },
    )
    verdict = decide(
        identity=revalidate(SEALED, SEALED),
        completeness_reasons=(),
        preflight_passed=True,
        assertions=evaluation,
        completion=CompletionObservation(Condition.TRUE, "one request", 1),
        evaluator_version=EVALUATOR,
        evidence_set_digest=EVIDENCE_SET,
    )
    assert verdict.outcome is Outcome.INCONCLUSIVE


def test_a_false_completion_fails_even_with_every_assertion_true() -> None:
    """Named in the prompt. Completion is a frozen required condition, not an optional extra: the
    reader can announce everything correctly about a page that submitted nothing."""
    verdict = _decide(
        completion=CompletionObservation(
            Condition.FALSE, "the application holds 0 requests", observed_count=0
        )
    )
    assert verdict.outcome is Outcome.FAIL
    assert any("completion false" in r for r in verdict.reasons)


def test_a_missing_producer_tail_makes_an_otherwise_passing_run_inconclusive() -> None:
    """Every assertion TRUE, completion TRUE, and the evidence incomplete. INV-06."""
    verdict = _decide(
        completeness_reasons=(
            "required producers have not closed their streams: observer:receipts",
        )
    )
    assert verdict.outcome is Outcome.INCONCLUSIVE
    assert any("observer:receipts" in r for r in verdict.reasons)


def test_a_corrupt_artifact_alongside_a_failure_is_inconclusive_not_fail() -> None:
    """The prompt's "failure plus corrupt artifact". The failure is real and the evidence around it
    is not trustworthy, so nothing is established."""
    verdict = _decide(
        assertion_values={ANNOUNCEMENT.assertion_id: _value(ANNOUNCEMENT, Condition.FALSE)},
        completeness_reasons=("stored artifacts do not match their recorded digests: …",),
    )
    assert verdict.outcome is Outcome.INCONCLUSIVE


def test_a_failed_preflight_makes_the_run_inconclusive() -> None:
    verdict = _decide(preflight_passed=False)
    assert verdict.outcome is Outcome.INCONCLUSIVE


def test_an_unknown_assertion_reports_which_one_and_why() -> None:
    """An INCONCLUSIVE that cannot say what was missing is indistinguishable from a broken
    evaluator."""
    verdict = _decide(
        assertion_values={
            ANNOUNCEMENT.assertion_id: _value(
                ANNOUNCEMENT, Condition.UNKNOWN, unknown_reason="speech capture timed out"
            )
        }
    )
    assert verdict.outcome is Outcome.INCONCLUSIVE
    assert any("speech capture timed out" in r for r in verdict.reasons)


# --- provenance ----------------------------------------------------------------------------------


def test_a_supervisor_cannot_author_an_application_observation() -> None:
    """The forged observer record. There is no retained artifact from which "the backend received
    exactly one request" follows, so a derived value there is the evaluator -- or a supervisor --
    inventing a backend observation and presenting it as one (CONTRACTS section 7)."""
    forged = AssertionOutcome(
        assertion_id=COMPLETION.assertion_id,
        kind=AssertionKind.TASK_COMPLETION,
        condition=Condition.TRUE,
        provenance=Provenance.EVALUATOR_DERIVED,
        evidence_refs=("event:3",),
    )
    with pytest.raises(ProvenanceError, match="inventing a backend observation"):
        assert_provenance_permitted(forged)


def test_the_evaluator_may_derive_a_reader_assertion() -> None:
    """Permitted, and the reason is specific: the transcript *is* the reader's own evidence."""
    assert_provenance_permitted(
        _value(ANNOUNCEMENT, Condition.TRUE, provenance=Provenance.EVALUATOR_DERIVED)
    )


@pytest.mark.parametrize(
    "kind",
    [AssertionKind.FORBIDDEN_EFFECT, AssertionKind.FUNCTIONAL_VALIDATION],
)
def test_no_non_reader_assertion_may_be_evaluator_derived(kind: AssertionKind) -> None:
    """Over the whole vocabulary rather than the one case in the prompt."""
    with pytest.raises(ProvenanceError):
        assert_provenance_permitted(
            AssertionOutcome(
                assertion_id="x",
                kind=kind,
                condition=Condition.TRUE,
                provenance=Provenance.EVALUATOR_DERIVED,
                evidence_refs=("event:1",),
            )
        )


def test_a_value_for_the_wrong_assertion_kind_is_refused() -> None:
    """The wrong-phrase-provenance case: a value claiming to decide a different kind of assertion is
    a value decided by a different observer."""
    with pytest.raises(ProvenanceError, match="observer entitled to decide it differs"):
        evaluate_assertions(
            (ANNOUNCEMENT,),
            {
                ANNOUNCEMENT.assertion_id: AssertionOutcome(
                    assertion_id=ANNOUNCEMENT.assertion_id,
                    kind=AssertionKind.TASK_COMPLETION,
                    condition=Condition.TRUE,
                    provenance=Provenance.OBSERVER_AUTHORED,
                    evidence_refs=("event:1",),
                )
            },
        )


def test_an_absent_observation_must_be_unknown() -> None:
    """Reading it as FALSE turns a capture failure into a reported accessibility defect."""
    with pytest.raises(ProvenanceError, match="absent observation is UNKNOWN"):
        AssertionOutcome(
            assertion_id="x",
            kind=AssertionKind.REQUIRED_ANNOUNCEMENT,
            condition=Condition.FALSE,
            provenance=Provenance.ABSENT,
        )


def test_a_definite_value_needs_an_evidence_reference() -> None:
    """A FALSE nobody can trace to an observation is not reviewable."""
    with pytest.raises(ProvenanceError, match="no evidence reference"):
        AssertionOutcome(
            assertion_id="x",
            kind=AssertionKind.REQUIRED_ANNOUNCEMENT,
            condition=Condition.FALSE,
            provenance=Provenance.OBSERVER_AUTHORED,
        )


def test_an_unknown_needs_a_reason() -> None:
    with pytest.raises(ProvenanceError, match="UNKNOWN without a reason"):
        AssertionOutcome(
            assertion_id="x",
            kind=AssertionKind.REQUIRED_ANNOUNCEMENT,
            condition=Condition.UNKNOWN,
            provenance=Provenance.ABSENT,
        )


def test_an_assertion_with_no_submitted_value_stays_required_as_unknown() -> None:
    """It is not dropped. Dropping it would shorten the list of conditions a PASS has to satisfy,
    which is exactly the direction a repair must not be able to push the evaluation (INV-16)."""
    evaluation = evaluate_assertions((ANNOUNCEMENT,), {})
    assert evaluation.conditions() == (Condition.UNKNOWN,)
    assert any("rather than being dropped" in r for r in evaluation.unknown_reasons())


# --- the independent observer ---------------------------------------------------------------------


class _Observer:
    def __init__(self, count: int, nonce: str = NONCE, fail: bool = False) -> None:
        self._count, self._nonce, self._fail = count, nonce, fail

    def count_effects(self, *, fixture_nonce: str, effect: str) -> EffectCount:
        if self._fail:
            raise ObserverError("connection refused")
        return EffectCount(
            fixture_nonce=self._nonce, effect=effect, count=self._count, observed_at="now"
        )


def test_a_matching_count_is_true() -> None:
    observation = observe_completion(
        _Observer(1), fixture_nonce=NONCE, effect="CREATE_TEST_REQUEST", expected_count=1
    )
    assert observation.condition is Condition.TRUE


def test_a_mismatched_count_is_false_and_says_it_measured_durable_state() -> None:
    observation = observe_completion(
        _Observer(0), fixture_nonce=NONCE, effect="CREATE_TEST_REQUEST", expected_count=1
    )
    assert observation.condition is Condition.FALSE
    assert "measurement of durable state" in observation.detail


def test_an_unreachable_observer_is_unknown_not_false() -> None:
    """The branch that matters. Treating "cannot reach the application" as FALSE would report a
    confirmed task failure every time the observer's network hiccuped."""
    observation = observe_completion(
        _Observer(0, fail=True),
        fixture_nonce=NONCE,
        effect="CREATE_TEST_REQUEST",
        expected_count=1,
    )
    assert observation.condition is Condition.UNKNOWN
    assert "not evidence that nothing happened" in observation.detail


def test_a_prior_fixtures_receipt_does_not_satisfy_this_run() -> None:
    """Named in the prompt. A receipt from an earlier run has a different nonce, and accepting it
    would let last week's success satisfy this run's completion assertion."""
    observation = observe_completion(
        _Observer(1, nonce="nonce-from-last-week"),
        fixture_nonce=NONCE,
        effect="CREATE_TEST_REQUEST",
        expected_count=1,
    )
    assert observation.condition is Condition.UNKNOWN
    assert "different run's fixture" in observation.detail


def test_the_observation_carries_no_oracle_material() -> None:
    """A caller holding this cannot read what the count was compared against, which keeps the answer
    key out of anything downstream that might carry it towards the navigator."""
    observation = observe_completion(
        _Observer(1), fixture_nonce=NONCE, effect="CREATE_TEST_REQUEST", expected_count=1
    )
    fields = set(type(observation).__dataclass_fields__)
    assert not any(f in fields for f in ("expected", "expected_count", "oracle", "observer_config"))


def test_the_observer_protocol_exposes_no_write() -> None:
    """Structural. The realistic version of this mistake is someone adding a `reset_fixture` helper
    because the observer already has a connection to the application."""
    from accessforge_persistence.evidence import ApplicationObserver

    assert observer_writes_nothing(ApplicationObserver) == ()
    assert [m for m in dir(ApplicationObserver) if not m.startswith("_")] == ["count_effects"]


# --- findings ------------------------------------------------------------------------------------


def test_only_a_complete_valid_failure_supports_reproduced() -> None:
    from accessforge_domain.evaluation import support_for_finding

    failed = _decide(
        completion=CompletionObservation(Condition.FALSE, "0 requests", observed_count=0)
    )
    support = support_for_finding(failed)
    assert support is not None and support.status is FindingStatus.REPRODUCED
    assert "established rather than merely seen" in support.rationale


def test_an_inconclusive_run_supports_only_a_candidate() -> None:
    """ "We observed a failure" and "we established a failure" are different claims, and only the
    second is a defect report someone should act on."""
    from accessforge_domain.evaluation import support_for_finding

    inconclusive = _decide(
        assertion_values={ANNOUNCEMENT.assertion_id: _value(ANNOUNCEMENT, Condition.FALSE)},
        completeness_reasons=("canonical chain has gaps",),
    )
    support = support_for_finding(inconclusive)
    assert support is not None and support.status is FindingStatus.CANDIDATE
    assert "not a confirmed defect" in support.rationale


def test_a_pass_supports_no_finding_at_all() -> None:
    """There is no such thing as a finding that something worked."""
    from accessforge_domain.evaluation import support_for_finding

    assert support_for_finding(_decide()) is None


# --- what the observer decides is not what the evaluator decides ----------------------------------


def test_the_completion_observer_is_the_application_not_the_reader() -> None:
    """The assertion-to-observer mapping is module 06's, and this test reads it rather than
    restating it: a completion assertion decided by the reader would mean the page's own
    announcement deciding whether the page worked."""
    from accessforge_domain.journeys.assertions import ASSERTION_OBSERVERS

    assert ASSERTION_OBSERVERS[AssertionKind.TASK_COMPLETION] is Observer.APPLICATION_OBSERVER
    assert ASSERTION_OBSERVERS[AssertionKind.REQUIRED_ANNOUNCEMENT] is Observer.READER
